/// Flutter icons SSizeIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SSizeIcons
///      fonts:
///       - asset: fonts/SSizeIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class SSizeIcons {
  SSizeIcons._();

  static const _kFontFam = 'SSizeIcons';

  static const IconData add_c = const IconData(0xe900, fontFamily: _kFontFam);
  static const IconData add_folder =
      const IconData(0xe901, fontFamily: _kFontFam);
  static const IconData add = const IconData(0xe902, fontFamily: _kFontFam);
  static const IconData align_center =
      const IconData(0xe903, fontFamily: _kFontFam);
  static const IconData align_left =
      const IconData(0xe904, fontFamily: _kFontFam);
  static const IconData align_light =
      const IconData(0xe905, fontFamily: _kFontFam);
  static const IconData align_right =
      const IconData(0xe906, fontFamily: _kFontFam);
  static const IconData align_txt =
      const IconData(0xe907, fontFamily: _kFontFam);
  static const IconData anchor = const IconData(0xe908, fontFamily: _kFontFam);
  static const IconData arrow_left =
      const IconData(0xe909, fontFamily: _kFontFam);
  static const IconData arrow_right =
      const IconData(0xe90a, fontFamily: _kFontFam);
  static const IconData arrow_square_left =
      const IconData(0xe90b, fontFamily: _kFontFam);
  static const IconData arrow_square_right =
      const IconData(0xe90c, fontFamily: _kFontFam);
  static const IconData bag = const IconData(0xe90d, fontFamily: _kFontFam);
  static const IconData battery_charging =
      const IconData(0xe90e, fontFamily: _kFontFam);
  static const IconData battery_empty =
      const IconData(0xe90f, fontFamily: _kFontFam);
  static const IconData battery_full =
      const IconData(0xe910, fontFamily: _kFontFam);
  static const IconData battery_middle =
      const IconData(0xe911, fontFamily: _kFontFam);
  static const IconData bin = const IconData(0xe912, fontFamily: _kFontFam);
  static const IconData bookmark =
      const IconData(0xe913, fontFamily: _kFontFam);
  static const IconData box = const IconData(0xe914, fontFamily: _kFontFam);
  static const IconData calculator =
      const IconData(0xe915, fontFamily: _kFontFam);
  static const IconData calendar_fill =
      const IconData(0xe916, fontFamily: _kFontFam);
  static const IconData calendar =
      const IconData(0xe917, fontFamily: _kFontFam);
  static const IconData camera = const IconData(0xe918, fontFamily: _kFontFam);
  static const IconData car = const IconData(0xe919, fontFamily: _kFontFam);
  static const IconData card_view =
      const IconData(0xe91a, fontFamily: _kFontFam);
  static const IconData cart = const IconData(0xe91b, fontFamily: _kFontFam);
  static const IconData chart = const IconData(0xe91c, fontFamily: _kFontFam);
  static const IconData chat_01 = const IconData(0xe91d, fontFamily: _kFontFam);
  static const IconData chat_02 = const IconData(0xe91e, fontFamily: _kFontFam);
  static const IconData chat_03 = const IconData(0xe91f, fontFamily: _kFontFam);
  static const IconData chat_wait =
      const IconData(0xe920, fontFamily: _kFontFam);
  static const IconData checkbox_list =
      const IconData(0xe921, fontFamily: _kFontFam);
  static const IconData checklist_done =
      const IconData(0xe922, fontFamily: _kFontFam);
  static const IconData chevron_down =
      const IconData(0xe923, fontFamily: _kFontFam);
  static const IconData chevron_left =
      const IconData(0xe924, fontFamily: _kFontFam);
  static const IconData chevron_right =
      const IconData(0xe925, fontFamily: _kFontFam);
  static const IconData chevron_up =
      const IconData(0xe926, fontFamily: _kFontFam);
  static const IconData close_folder =
      const IconData(0xe927, fontFamily: _kFontFam);
  static const IconData close = const IconData(0xe928, fontFamily: _kFontFam);
  static const IconData cloud_download =
      const IconData(0xe929, fontFamily: _kFontFam);
  static const IconData cloud_unload =
      const IconData(0xe92a, fontFamily: _kFontFam);
  static const IconData coffee = const IconData(0xe92b, fontFamily: _kFontFam);
  static const IconData color_circle =
      const IconData(0xe92c, fontFamily: _kFontFam);
  static const IconData computer =
      const IconData(0xe92d, fontFamily: _kFontFam);
  static const IconData copy = const IconData(0xe92e, fontFamily: _kFontFam);
  static const IconData cube = const IconData(0xe92f, fontFamily: _kFontFam);
  static const IconData delete = const IconData(0xe931, fontFamily: _kFontFam);
  static const IconData diagram_02 =
      const IconData(0xe932, fontFamily: _kFontFam);
  static const IconData diagram = const IconData(0xe933, fontFamily: _kFontFam);
  static const IconData document =
      const IconData(0xe934, fontFamily: _kFontFam);
  static const IconData download =
      const IconData(0xe935, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe936, fontFamily: _kFontFam);
  static const IconData exclamation =
      const IconData(0xe937, fontFamily: _kFontFam);
  static const IconData export_icon =
      const IconData(0xe938, fontFamily: _kFontFam);
  static const IconData eye = const IconData(0xe939, fontFamily: _kFontFam);
  static const IconData eyephones =
      const IconData(0xe93a, fontFamily: _kFontFam);
  static const IconData female = const IconData(0xe93b, fontFamily: _kFontFam);
  static const IconData Fillexclamation =
      const IconData(0xe93c, fontFamily: _kFontFam);
  static const IconData Fillinfo =
      const IconData(0xe93d, fontFamily: _kFontFam);
  static const IconData filter = const IconData(0xe93e, fontFamily: _kFontFam);
  static const IconData filters = const IconData(0xe93f, fontFamily: _kFontFam);
  static const IconData flag = const IconData(0xe940, fontFamily: _kFontFam);
  static const IconData focus = const IconData(0xe941, fontFamily: _kFontFam);
  static const IconData folder = const IconData(0xe942, fontFamily: _kFontFam);
  static const IconData guard = const IconData(0xe943, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe944, fontFamily: _kFontFam);
  static const IconData history = const IconData(0xe945, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe946, fontFamily: _kFontFam);
  static const IconData import_icon =
      const IconData(0xe947, fontFamily: _kFontFam);
  static const IconData info = const IconData(0xe948, fontFamily: _kFontFam);
  static const IconData insta = const IconData(0xe949, fontFamily: _kFontFam);
  static const IconData install = const IconData(0xe94a, fontFamily: _kFontFam);
  static const IconData key = const IconData(0xe94b, fontFamily: _kFontFam);
  static const IconData layout = const IconData(0xe94c, fontFamily: _kFontFam);
  static const IconData lift = const IconData(0xe94d, fontFamily: _kFontFam);
  static const IconData list = const IconData(0xe94e, fontFamily: _kFontFam);
  static const IconData location_fill =
      const IconData(0xe94f, fontFamily: _kFontFam);
  static const IconData location =
      const IconData(0xe950, fontFamily: _kFontFam);
  static const IconData lock_opened =
      const IconData(0xe951, fontFamily: _kFontFam);
  static const IconData lock = const IconData(0xe952, fontFamily: _kFontFam);
  static const IconData magic = const IconData(0xe953, fontFamily: _kFontFam);
  static const IconData mail = const IconData(0xe954, fontFamily: _kFontFam);
  static const IconData male = const IconData(0xe955, fontFamily: _kFontFam);
  static const IconData map = const IconData(0xe956, fontFamily: _kFontFam);
  static const IconData microphone =
      const IconData(0xe957, fontFamily: _kFontFam);
  static const IconData minus_c = const IconData(0xe958, fontFamily: _kFontFam);
  static const IconData minus = const IconData(0xe959, fontFamily: _kFontFam);
  static const IconData more_horizontal =
      const IconData(0xe95a, fontFamily: _kFontFam);
  static const IconData more_vertical =
      const IconData(0xe95b, fontFamily: _kFontFam);
  static const IconData move = const IconData(0xe95c, fontFamily: _kFontFam);
  static const IconData music = const IconData(0xe95d, fontFamily: _kFontFam);
  static const IconData notification =
      const IconData(0xe95e, fontFamily: _kFontFam);
  static const IconData paperbox =
      const IconData(0xe95f, fontFamily: _kFontFam);
  static const IconData pause = const IconData(0xe960, fontFamily: _kFontFam);
  static const IconData pen_big = const IconData(0xe961, fontFamily: _kFontFam);
  static const IconData pen_small =
      const IconData(0xe962, fontFamily: _kFontFam);
  static const IconData people_card_fill =
      const IconData(0xe963, fontFamily: _kFontFam);
  static const IconData people_card =
      const IconData(0xe964, fontFamily: _kFontFam);
  static const IconData personal_card =
      const IconData(0xe965, fontFamily: _kFontFam);
  static const IconData picture = const IconData(0xe966, fontFamily: _kFontFam);
  static const IconData pill = const IconData(0xe967, fontFamily: _kFontFam);
  static const IconData play = const IconData(0xe968, fontFamily: _kFontFam);
  static const IconData portfolio =
      const IconData(0xe969, fontFamily: _kFontFam);
  static const IconData price = const IconData(0xe96a, fontFamily: _kFontFam);
  static const IconData print = const IconData(0xe96b, fontFamily: _kFontFam);
  static const IconData qr = const IconData(0xe96c, fontFamily: _kFontFam);
  static const IconData Quit = const IconData(0xe96d, fontFamily: _kFontFam);
  static const IconData read = const IconData(0xe96e, fontFamily: _kFontFam);
  static const IconData renew_01 =
      const IconData(0xe96f, fontFamily: _kFontFam);
  static const IconData renew_02 =
      const IconData(0xe970, fontFamily: _kFontFam);
  static const IconData screen = const IconData(0xe971, fontFamily: _kFontFam);
  static const IconData scroll = const IconData(0xe972, fontFamily: _kFontFam);
  static const IconData search_close =
      const IconData(0xe973, fontFamily: _kFontFam);
  static const IconData search_open =
      const IconData(0xe974, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe975, fontFamily: _kFontFam);
  static const IconData send = const IconData(0xe976, fontFamily: _kFontFam);
  static const IconData server = const IconData(0xe977, fontFamily: _kFontFam);
  static const IconData settings =
      const IconData(0xe978, fontFamily: _kFontFam);
  static const IconData share = const IconData(0xe979, fontFamily: _kFontFam);
  static const IconData square_delete =
      const IconData(0xe97a, fontFamily: _kFontFam);
  static const IconData square_exclamation =
      const IconData(0xe97b, fontFamily: _kFontFam);
  static const IconData square_info =
      const IconData(0xe97c, fontFamily: _kFontFam);
  static const IconData square_minus =
      const IconData(0xe97d, fontFamily: _kFontFam);
  static const IconData square_plus =
      const IconData(0xe97e, fontFamily: _kFontFam);
  static const IconData square_success =
      const IconData(0xe97f, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe980, fontFamily: _kFontFam);
  static const IconData stop = const IconData(0xe981, fontFamily: _kFontFam);
  static const IconData success = const IconData(0xe982, fontFamily: _kFontFam);
  static const IconData switchoff =
      const IconData(0xe983, fontFamily: _kFontFam);
  static const IconData tag = const IconData(0xe984, fontFamily: _kFontFam);
  static const IconData target = const IconData(0xe985, fontFamily: _kFontFam);
  static const IconData thunder = const IconData(0xe986, fontFamily: _kFontFam);
  static const IconData timemachine =
      const IconData(0xe987, fontFamily: _kFontFam);
  static const IconData unload = const IconData(0xe988, fontFamily: _kFontFam);
  static const IconData user_fill =
      const IconData(0xe989, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe98a, fontFamily: _kFontFam);
  static const IconData wallet = const IconData(0xe98b, fontFamily: _kFontFam);
  static const IconData winner = const IconData(0xe98c, fontFamily: _kFontFam);
}
